
    export const FETCH_USERS_START =  'FETCH_USERS_START';
    export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
    export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

    export const REGISTER_START =  'REGISTER_START';
    export const REGISTER_SUCCESS =  'REGISTER_SUCCESS';
    export const REGISTER_FAILURE =  'REGISTER_FAILURE';

  